### ISSUE TITLE
Server compile end up with error on debian

### ISSUE THREAD

**Issue by CompuRoot** [francoismichel/ssh3#47]
```
$go version
go version go1.21.5 linux/amd64


$ go build -o ssh3-server cli/server/main.go
# ssh3/linux_server
linux_server/authorized_identities.go:39:50: undefined: linux_util.User
linux_server/authorized_identities.go:131:37: undefined: linux_util.User
linux_server/authorized_identities.go:171:53: undefined: linux_util.User
linux_server/auth.go:80:25: undefined: linux_util.UserPasswordAuthentication
linux_server/handlers.go:51:27: undefined: linux_util.GetUser
```

**Comment by francoismichel** [comment]
This is because building the server requires `CGO_ENABLED=1` when building. If it is not set, it will ignore files with `import "C"` in it, causing the error above.

If you hae `gcc` installed, you should be able to install the server doing the following:

    go build -o ssh3-server cli/server/main.go

Thanks for filing the issue ! I'll update the README.
