### ISSUE TITLE
ERR cannot parse identity line: unknown identity format: # OpenSSH authorized_keys file format is described in sshd(8) manual page.

### ISSUE THREAD

**Issue by vt-alt** [francoismichel/ssh3#50]
Comments in `authorized_keys` cause an error: `ERR cannot parse identity line: unknown identity format: # OpenSSH authorized_keys file format is described in sshd(8) manual page.`

ALT Linux have comment in `authorized_keys` at the 1st line for each user by default:
```
# OpenSSH authorized_keys file format is described in sshd(8) manual page.
```

ps. Alto it's common for users to comment old keys instead of deleting them so this is not an error.

**Comment by francoismichel** [comment]
I am using the [`ssh_config`](https://pkg.go.dev/github.com/kevinburke/ssh_config) package to parse the config and I am surprised it does not handle that case. Maybe there is a bad edge case with comments in the first line.
I'll have a look and do a quick fix if the problem comes from github.com/kevinburke/ssh_config.

**Comment by vt-alt** [comment]
Thanks for the fix!
