### ISSUE TITLE
ssh3 doesnt using .profile/.bashrc of server

### ISSUE THREAD

**Issue by vaminakov** [francoismichel/ssh3#69]
Like in subject. ssh3 doesnt using .profile/.bashrc of server on login, and there are no option to inherit environment.

**Comment by francoismichel** [comment]
Nice catch !

`.bashrc` is run, but not `.profile` indeed. For that, we need to run the shell as a login shell.
We just need to set the first argv to `-[shell_name]` when running the shell called `[shell_name]`
for instance, seting `argv[0]` to `-bash` instead of `bash` when the user shell is `bash`.

That will be an easy fix that could be dont for the next release.

**Comment by francoismichel** [comment]
Fixed by https://github.com/francoismichel/ssh3/commit/effbb009215bd269c91a8ca0f9aed0db8b736f41

Thank you for the issue!
